### ISSUE TITLE
Reset sheep to the team spawn if they are outside for too long

### ISSUE THREAD

**Issue by SuperCoder7979** [NucleoidMC/farmy-feud#2]

**Comment by Restioson** [comment]
Hacky fix for #4?

**Comment by SuperCoder7979** [comment]
Heh I suppose it is 😅 I was thinking that if a sheep was outside of spawn for 30 or 60 seconds, it would be teleported back to the spawn. That way, people can't use it to cheat.

**Comment by Restioson** [comment]
Oh, I see what you mean... That's a different issue, yep.
